
ALL : hygiene.rdf tripadvisor.rdf yelp.rdf facebook.rdf twitter.rdf gplus.rdf

clean:
	rm hygiene.rdf tripadvisor.rdf yelp.rdf facebook.rdf twitter.rdf gplus.rdf

hygiene.rdf:
	cwm --n3 hygiene.n3 --rdf > hygiene.rdf

tripadvisor.rdf:
	cwm --n3 tripadvisor.n3 --rdf > tripadvisor.rdf

yelp.rdf:
	cwm --n3 yelp.n3 --rdf > yelp.rdf

facebook.rdf:
	cwm --n3 facebook.n3 --rdf > facebook.rdf

twitter.rdf:
	cwm --n3 twitter.n3 --rdf > twitter.rdf

gplus.rdf:
	cwm --n3 gplus.n3 --rdf > gplus.rdf

